-- UI plugins configuration
require("david.plugins.ui.bufferline")
require("david.plugins.ui.colorscheme")
require("david.plugins.ui.dressing")
require("david.plugins.ui.indent-blankline")
require("david.plugins.ui.lualine")
require("david.plugins.ui.neo-tree")
require("david.plugins.ui.noice")
require("david.plugins.ui.notify")
require("david.plugins.ui.nvim-cmp")
require("david.plugins.ui.telescope")
require("david.plugins.ui.todo-comments")
require("david.plugins.ui.trouble")
require("david.plugins.ui.vim-maximizer")
require("david.plugins.ui.which-key")